### PR TITLE
Add HuggingFace packages

### PR DESCRIPTION
**Pull request by augustin-cramer**
Add HuggingFace's packages to extra_libraries.txt

### CODE REVIEW

**Comment by frcaud** [comment]
Thanks @augustin-cramer. Please add these packages in environment.yml also.

**Comment by augustin-cramer** [comment]
no conflict issues during package installation

**Comment by augustin-cramer** [comment]
@frcaud done

**Comment by frcaud** [comment]
thx @augustin-cramer

**Pull request merged**
